### ISSUE TITLE
Codeblocks are displaying incorrectly

### ISSUE THREAD

**Issue by advaith1** [pages-themes/time-machine#6] opened 2017-12-08 02:40 UTC
![](https://cdn.discordapp.com/attachments/252296452708106240/388520005530157057/unknown.png)

This has been tested on Opera 51.0.2791.0 on Windows 10 and Firefox on Ubuntu.

**Comment by MV10** [comment] 2017-12-22 15:16
Same problem is visible in Chrome 63.0.3239.84 on Win10.

**Comment by benbalter** [comment] 2017-12-26 15:56
I believe this is a duplicate of https://github.com/pages-themes/time-machine/issues/1.

**Closed by benbalter** 2017-12-26 15:56 UTC

**Comment by advaith1** [comment] 2017-12-29 04:53
@benbalter It's not, since that bug is safari only. In chrome I see this bug but not #1, so they must have different causes.

**Comment by aaaronic** [comment] 2018-05-21 20:16
I also still see this exact bug on the demo site in Chrome 66 on MacOS Sierra.
